export const TYOA = {
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  skills: {
    animals: "TYOA.skills.animals",
    athletics: "TYOA.skills.athletics",
    communication: "TYOA.skills.communication",
    crafting: "TYOA.skills.crafting",
    fighting: "TYOA.skills.fighting",
    knowledge: "TYOA.skills.knowledge",
    leadership: "TYOA.skills.leadership",
    marksmanship: "TYOA.skills.marksmanship",
    performance: "TYOA.skills.performance",
    perseverance: "TYOA.skills.perseverance",
    sailing: "TYOA.skills.sailing",
    stealth: "TYOA.skills.stealth",
    survival: "TYOA.skills.survival",
    toughness: "TYOA.skills.toughness",
    metamancy: "TYOA.skills.metamancy",
    biomancy: "TYOA.skills.biomancy",
    chronomancy: "TYOA.skills.chronomancy",
    elemancy: "TYOA.skills.elemancy",
    locomancy: "TYOA.skills.locomancy",
    necromancy: "TYOA.skills.necromancy",
    psychomancy: "TYOA.skills.psychomancy",
  },
  encumbLocation: {
    readied: "TYOA.items.readied",
    stowed: "TYOA.items.stowed",
    other: "TYOA.items.other"
  },
  weightless: {
    never: "TYOA.items.WeightlessNever",
    whenReadied: "TYOA.items.WeightlessReadied",
    whenStowed: "TYOA.items.WeightlessStowed"
  },
  attackSkills: {
    fighting: "TYOA.skills.fighting",
    marksmanship: "TYOA.skills.marksmanship",
    metamancy: "TYOA.skills.metamancy",
    biomancy: "TYOA.skills.biomancy",
    chronomancy: "TYOA.skills.chronomancy",
    elemancy: "TYOA.skills.elemancy",
    locomancy: "TYOA.skills.locomancy",
    necromancy: "TYOA.skills.necromancy",
    psychomancy: "TYOA.skills.psychomancy",

  },
  armor : {
    unarmored: "TYOA.armor.unarmored",
    light: "TYOA.armor.light",
    medium: "TYOA.armor.medium",
    heavy: "TYOA.armor.heavy",
    shield: "TYOA.armor.shield",
  },
  colors: {
    green: "TYOA.colors.green",
    red: "TYOA.colors.red",
    yellow: "TYOA.colors.yellow",
    purple: "TYOA.colors.purple",
    blue: "TYOA.colors.blue",
    orange: "TYOA.colors.orange",
    white: "TYOA.colors.white"
  },
  tags: {
    melee: "TYOA.items.Melee",
    missile: "TYOA.items.Missile",
    TH: "TYOA.items.2H",
    B: "TYOA.items.B",
    CH: "TYOA.items.CH",
    E: "TYOA.items.E",
    L: "TYOA.items.L",
    LL: "TYOA.items.LL",
    M: "TYOA.items.M",
    MO: "TYOA.items.MO",
    N: "TYOA.items.N",
    P: "TYOA.items.P",
    R: "TYOA.items.R",
    S: "TYOA.items.S",
    SR: "TYOA.items.SR",
    T: "TYOA.items.T",
  },
  tag_images: {
    melee: "systems/tyoa/assets/melee.png",
    missile: "systems/tyoa/assets/missile.png",
    TH: "systems/tyoa/assets/twohanded.png",
    B: "systems/tyoa/assets/brace.png",
    CH: "systems/tyoa/assets/charge.png",
    E: "systems/tyoa/assets/single_shot.png", // TODO
    L: "systems/tyoa/assets/long.png",
    LL: "systems/tyoa/assets/less_lethal.png",
    M: "systems/tyoa/assets/dragon.png",
    MO: "systems/tyoa/assets/skills/ride.png",
    N: "systems/tyoa/assets/numerous.png",
    P: "systems/tyoa/assets/precisely_murderous.png",
    R: "systems/tyoa/assets/reload.png",
    S: "systems/tyoa/assets/subtle.png",
    SR: "systems/tyoa/assets/slow_reload.png",
    T: "systems/tyoa/assets/throwable.png"
  },
  tag_desc: {
    melee: "TYOA.items.desc.Melee",
    missile: "TYOA.items.desc.Missile",
    TH: "TYOA.items.desc.2H",
    B: "TYOA.items.desc.B",
    CH: "TYOA.items.desc.CH",
    E: "TYOA.items.desc.E",
    L: "TYOA.items.desc.L",
    LL: "TYOA.items.desc.LL",
    M: "TYOA.items.desc.M",
    MO: "TYOA.items.desc.MO",
    N: "TYOA.items.desc.N",
    P: "TYOA.items.desc.P",
    R: "TYOA.items.desc.R",
    S: "TYOA.items.desc.S",
    SR: "TYOA.items.desc.SR",
    T: "TYOA.items.desc.T",
  },
  assetTypes: {
    cunning: "TYOA.asset.cunning",
    force: "TYOA.asset.force",
    wealth: "TYOA.asset.wealth"
  },
  assetMagic: {
    none: "TYOA.asset.magicNone",
    low: "TYOA.asset.magicLow",
    medium: "TYOA.asset.magicMedium",
    high: "TYOA.asset.magicHigh",
  }
};